# Generated by Django 5.2.9 on 2025-12-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='budget_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
